INSERT INTO dominios.distritos_ilhas (cod,designacao) VALUES
	 ('01','AVEIRO'),
	 ('02','BEJA'),
	 ('03','BRAGA'),
	 ('04','BRAGANÇA'),
	 ('05','CASTELO BRANCO'),
	 ('06','COIMBRA'),
	 ('07','ÉVORA'),
	 ('08','FARO'),
	 ('09','GUARDA'),
	 ('44','ILHA DA GRACIOSA'),
	 ('31','ILHA DA MADEIRA'),
	 ('48','ILHA DAS FLORES'),
	 ('32','ILHA DE PORTO SANTO'),
	 ('41','ILHA DE SANTA MARIA'),
	 ('45','ILHA DE SÃO JORGE'),
	 ('42','ILHA DE SÃO MIGUEL'),
	 ('47','ILHA DO FAIAL'),
	 ('46','ILHA DO PICO'),
	 ('43','ILHA TERCEIRA'),
	 ('10','LEIRIA'),
	 ('11','LISBOA'),
	 ('12','PORTALEGRE'),
	 ('13','PORTO'),
	 ('14','SANTARÉM'),
	 ('15','SETÚBAL'),
	 ('16','VIANA DO CASTELO'),
	 ('17','VILA REAL'),
	 ('18','VISEU'),
	 ('49','ILHA CORVO');
